---
title: "FreqAmp"
author: "JDS"
date: "March 8, 2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggpubr)
library(grid)
library(gridExtra)
# library(plot3D)
```

# group by stretch vs shorten

```{r, include = F}
data = read.csv('C:/Users/Jake/Documents/Data/AmpFreq.csv')

# data = data[data$Aff1type == 'Ia' ,]
unID = rep('str', dim(data)[1])
for (i in 1:dim(data)[1]){
  unID[i] = paste("Cell", data[i, 'Cell'], "f", data[i, "Freq"])
}
data = cbind(data, unID)
```

```{r}
# grouping = unID
iba_amp = ggplot(data, aes(x = Amp,
                 y = Aff1_ib,
                 color = interaction(factor(Freq), factor(Cell)),
                 group = interaction(factor(Freq), factor(Cell)))) +
  geom_point(aes(color = interaction(factor(Freq), factor(Cell)))) +
  # geom_smooth(aes(group = interaction(factor(Freq), factor(Cell)), 
  #                 color = interaction(factor(Freq), factor(Cell))), 
  #             formula = y ~ poly(x, 2),
              # method = 'lm', 
              # se = F) +
  xlab("Amplitude") +
  ylab("Initial Burst")

mifr_amp = ggplot(data, aes(x = Amp,
                 y = Aff1_s,
                 color = factor(Cell), 
                 group = factor(Cell))) +
  geom_point(aes(color = factor(Cell))) +
  # geom_smooth(aes(color = factor(Cell)), se = F) +
  xlab("Amplitude") +
  ylab("Avg. St. State Peak FR")

IFRplot = ggarrange(iba_amp, mifr_amp, nrow = 1, common.legend = T)
IFRplot
ggsave('C:/Users/Jake/Documents/Lab/IFR_Amp.png', IFRplot, device = 'png')
```

```{r}
iF_amp = ggplot(data, aes(x = Amp,
                 y = Fmt_init,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Amplitude") +
  ylab("Initial Peak Force")

mF_amp = ggplot(data, aes(x = Amp,
                 y = Fmt_s,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Amplitude") +
  ylab("Avg. S.State Peak Force")
iF_amp
Fplot = ggarrange(iF_amp, mF_amp, nrow = 1, common.legend = T)
Fplot
ggsave('C:/Users/Jake/Documents/Lab/F_Amp.png', Fplot, device = 'png')
```

```{r}
iLf_amp = ggplot(data, aes(x = Amp,
                 y = Lf_init,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Amplitude") +
  ylab("Initial Fas. Stretch")

mLf_amp = ggplot(data, aes(x = Amp,
                 y = Lf_s,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Amplitude") +
  ylab("Avg. S.State Peak Fas. Stretch")

Lplot = ggarrange(iLf_amp, mLf_amp, nrow = 1, common.legend = T)
Lplot
ggsave('C:/Users/Jake/Documents/Lab/L_Amp.png', Lplot, device = 'png')
```

```{r}
iFR_iLf = ggplot(data, aes(x = Lf_init,
                 y = Aff1_ib,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Initial Fas. Stretch") +
  ylab("Initial Burst")

mFR_mLf = ggplot(data, aes(x = Lf_s,
                 y = Aff1_s,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Avg. S.State Peak Fas. Stretch") +
  ylab("Avg. S.State Peak FR")

IFR_lfplot = ggarrange(iFR_iLf, mFR_mLf, nrow = 1, common.legend = T)
IFR_lfplot
ggsave('C:/Users/Jake/Documents/Lab/IFR_LfAmp.png', IFR_lfplot, device = 'png')
```


```{r}
iF_iLf = ggplot(data, aes(x = Lf_init,
                 y = Fmt_init,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Initial Fas. Stretch") +
  ylab("Initial Force")

mF_mLf = ggplot(data, aes(x = Lf_s,
                 y = Fmt_s,
                 color = factor(Freq), 
                 group = unID)) +
  geom_point(aes(color = factor(Freq))) +
  geom_line(aes(color = factor(Freq))) +
  xlab("Avg. S.State Peak Fas. Stretch") +
  ylab("Avg. S.State Peak Force")

F_Lfplot = ggarrange(iF_iLf, mF_mLf, nrow = 1, common.legend = T)
F_Lfplot
ggsave('C:/Users/Jake/Documents/Lab/F_LfAmp.png', F_Lfplot, device = 'png')
```

```{r}
IBAplot = scatter3D(x = data$Freq,
                    y = data$Amp, 
                    z = data$Aff1_ib,
                    xlab = "Freq",
                    ylab = "Amp",
                    zlab = "IBA",
                    phi = 20,
                    theta = -45,
                    type = 'h',
                    ticktype = "simple",
                    bty = "g",
                    pch = 19,
                    cex = 1.5)
ssFRplot = scatter3D(x = data$Freq,
                    y = data$Amp, 
                    z = data$Aff1_s,
                    xlab = "Freq",
                    ylab = "Amp",
                    zlab = "S.S. FR",
                    phi = 20,
                    theta = -45,
                    type = 'h',
                    ticktype = "simple",
                    bty = "g",
                    pch = 19,
                    cex = 1.5)

# Error in match.arg(bty) : 'arg' should be one of “b”, “b2”, “f”, “g”, “bl”, “bl2”, “u”, “n”
IBAplot
ssFRplot

ggsave('C:/Users/Jake/Documents/Lab/IFR_Amp.png', IBAplot, device = 'png')
ggsave('C:/Users/Jake/Documents/Lab/IFR_Amp.png', ssFRplot, device = 'png')
```


```{r}
scatter3D(x = data$Freq,
                    y = data$Amp, 
                    z = data$Fmt_init,
                    xlab = "Freq",
                    ylab = "Amp",
                    zlab = "Init. Force",
                    phi = 20,
                    theta = -45,
                    type = 'h',
                    ticktype = "simple",
                    bty = "g",
                    pch = 19,
                    cex = 1.5)
```

