function plotProcData(procdata, opt)
subplot(421)
plot(procdata.time, procdata.Lmt)
ylabel('L_{MTU}')
ax = gca;
subplot(422)
plot(procdata.time, procdata.dLmt)
ylabel('v_{MTU}')
subplot(423)
plot(procdata.time, procdata.Fmt)
ylabel('F_{MTU}')
subplot(424)
plot(procdata.time, procdata.dFmt)
ylabel('Y_{MTU}')
if strcmp(opt, 'sonos')
    subplot(425)
    plot(procdata.time, procdata.Lf)
    ylabel('L_{fas}')
    subplot(426)
    plot(procdata.time, procdata.dLf)
    ylabel('v_{fas}')
end
subplot(427)
plot(procdata.spiketimes, procdata.ifr, '.k')
xlim(ax.XAxis.Limits)
xlabel('time')
ylabel('IFR')