---
title: "JDS_spindle_spring_analysis"
author: "JDS"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(grid)
library(gridExtra)
library(ggbeeswarm)
library(knitr)
library(kableExtra)
library(lmerTest)
library(psych)
library(sjPlot)
library(rstatix)
# source('~/GitHub/SpindleGrant/SpindleSpring/functions.R')
```

##Parse data frames
```{r}
df = read.csv('/Users/jacobstephens/Documents/summaryTable-19-Jun-2023.csv')

#global filters
df$KT = factor(df$KT, levels = c("T", "C")) # set KT as a factor to make analysis easier later on

# create unique cell vector
unID = df$Address
df <- cbind(df, unID)
for (i in 1:dim(df)[1]){
  df$unID[i] = paste(df$ID[i], df$cell[i], sep = 'cell')
}

# Parse
tridf <- df[df$type == 'triangle', ] # data frame of triangles
rampdf <- df[df$type == 'ramp', ] # ramps
sinedf <- df[df$type == 'sine', ] # sines

scHD <- tridf$trisc1 - tridf$trisc2
mifrHD <- tridf$trimifr1 - tridf$trimifr2
tridf <- cbind(tridf, scHD, mifrHD)

# Keep afferents with data in both CTRL and SEE
triTaffs <- unique(tridf$unID[which(tridf$KT == 'T')]) # find afferents with control data
triCaffs <- unique(tridf$unID[which(tridf$KT == 'C')]) # find afferents with SEE data
trikeepaffs <- triCaffs[is.element(triCaffs, triTaffs)] # afferents with both
tridf <- subset(tridf, is.element(tridf$unID, trikeepaffs)) # subset to afferents with Ctrl and SEE data

rampTaffs <- unique(rampdf$unID[which(rampdf$KT == 'T')])
rampCaffs <- unique(rampdf$unID[which(rampdf$KT == 'C')])
rampkeepaffs <- rampCaffs[is.element(rampCaffs, rampTaffs)]
rampdf <- subset(rampdf, is.element(rampdf$unID, rampkeepaffs))

sineTaffs <- unique(sinedf$unID[which(sinedf$KT == 'T')])
sineCaffs <- unique(sinedf$unID[which(sinedf$KT == 'C')])
sinekeepaffs <- sineCaffs[is.element(sineCaffs, sineTaffs)]
sinedf <- subset(sinedf, is.element(sinedf$unID, sinekeepaffs))
```

# Fig 1
```{r}
# Stiffness analysis
# use linear mixed model with SEE as a fixed effect and individual animal as
# a random effect
df %>% lmerTest::lmer(formula = dLfdLmt ~ KT + (1|ID)) %>% summary()
df %>% lmerTest::lmer(formula = kMTU ~ KT + (1|ID)) %>% summary()
df %>% lmerTest::lmer(formula = kFas ~ KT + (1|ID)) %>% summary()

# per stretch type
rampdf %>% lmerTest::lmer(formula = dLfdLmt ~ KT + (1|ID)) %>% summary()
tridf %>% lmerTest::lmer(formula = dLfdLmt ~ KT + (1|ID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = dLfdLmt ~ KT + (1|ID)) %>% summary()

rampdf %>% lmerTest::lmer(formula = kMTU ~ KT + (1|ID)) %>% summary()
tridf %>% lmerTest::lmer(formula = kMTU ~ KT + (1|ID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = kMTU ~ KT + (1|ID)) %>% summary()

rampdf %>% lmerTest::lmer(formula = kFas ~ KT + (1|ID)) %>% summary()
tridf %>% lmerTest::lmer(formula = kFas ~ KT + (1|ID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = kFas ~ KT + (1|ID)) %>% summary()

# stiffness comparison plots
dLfdLmtrampplot <- rampdf %>%
  ggplot(aes(x = KT, y = dLfdLmt)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.2, height = 0) + 
  geom_smooth(aes(group = ID), method = 'lm', se = F) +
  ylim(c(0, .8)) +
  theme_bw()

kMTUrampplot <- rampdf %>%
  ggplot(aes(x = KT, y = kMTU)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.2, height = 0) + 
  geom_smooth(aes(group = ID), method = 'lm', se = F) +
  ylim(c(0, .8)) +
  theme_bw()

kFasrampplot <- rampdf %>%
  ggplot(aes(x = KT, y = kFas)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.2, height = 0) + 
  geom_smooth(aes(group = ID), method = 'lm', se = F) +
  ylim(c(0, 2)) +
  theme_bw()

ggarrange(dLfdLmtrampplot, kMTUrampplot, kFasrampplot, nrow = 1)
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig1stats.eps', device = 'eps', plot = last_plot(), width = 4600, height = 944, units = 'px')
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig1stats.jpg', device = 'jpg', plot = last_plot(), width = 4600, height = 944, units = 'px')
```

# Fig 2
```{r}
# Sines IFR comparisons
sinedf %>% lmerTest::lmer(formula = peakifr ~ KT + (1|unID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = meanifr ~ KT + (1|unID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = cyclespikect ~ KT + (1|unID)) %>% summary()

# confirm force and length changes
sinedf %>% lmerTest::lmer(formula = FasExc ~ KT + (1|unID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = FasExc ~ KT + (1|unID)) %>% summary()

# Sine regression R2
describe(sinedf[c('rLmt', 'rLf', 'rFmt', 'rvmt', 'rvf')])
# compare regression slopes
sinedf %>% lmerTest::lmer(formula = mLf ~ KT + (1|unID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = mvf ~ KT + (1|unID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = mFmt ~ KT + (1|unID)) %>% summary()
sinedf %>% lmerTest::lmer(formula = bFmt ~ KT + (1|unID)) %>% summary()

# Sines IFR comparison plots
sinepkplot <- sinedf %>% ggplot(aes(x = KT, y = peakifr)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(color = unID, group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 210)) +
  theme_bw()
sinemeanplot <- sinedf %>% ggplot(aes(x = KT, y = meanifr)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(color = unID, group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 200)) +
  theme_bw()
ggarrange(sinepkplot, sinemeanplot, nrow = 2, ncol= 1, common.legend = T)
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig2stats.eps', device = 'eps', plot = last_plot(), width = 2, height = 8, units = 'in')
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig2stats.jpg', device = 'jpg', plot = last_plot(), width = 2, height = 8, units = 'in')
```

# Fig 3
```{r}
# Ramps IFR comparison
rampdf %>% lmerTest::lmer(formula = IBA ~ KT + (1|unID)) %>% summary() # IB vs compliance
rampdf %>% lmerTest::lmer(formula = DRA ~ KT + (1|unID)) %>% summary() # DR vs compliance
rampdf %>% lmerTest::lmer(formula = DI ~ KT + (1|unID)) %>% summary() # DI vs compliance
rampdf %>% lmerTest::lmer(formula = SRA ~ KT + (1|unID)) %>% summary() # SR vs compliance

rampdf$IBA[rampdf$KT == 'T'] %>% describe() # summary stats for IB in CTRL
rampdf$IBA[rampdf$KT == 'C'] %>% describe() # summary stats for IB w SEE

# Ramps regressions
describe(rampdf[c('rLmt', 'rLf', 'rFmt', 'rvmt', 'rvf')]) # summary stats for regression R2s

# compare regression slopes
rampdf %>% lmerTest::lmer(formula = mLf ~ KT + (1|unID)) %>% summary() # IFR/Lf vs compliance
rampdf %>% lmerTest::lmer(formula = mLmt ~ KT + (1|unID)) %>% summary() # IFR/Lmt vs compliance
rampdf %>% lmerTest::lmer(formula = mvf ~ KT + (1|unID)) %>% summary() # IFR/vf vs compliance
rampdf %>% lmerTest::lmer(formula = mvmt ~ KT + (1|unID)) %>% summary() # IFR/vmt vs compliance
rampdf %>% lmerTest::lmer(formula = mFmt ~ KT + (1|unID)) %>% summary() # IFR/Fmt vs compliance

rampdf$mFmt[rampdf$KT == 'T'] %>% describe() # IFR/Fmt in CTRL
rampdf$mFmt[rampdf$KT == 'C'] %>% describe() # IFR/Fmt w SEE
rampdf$rFmt[rampdf$KT == 'T'] %>% describe() # IFR/Fmt R2 in CTRL
rampdf$rFmt[rampdf$KT == 'C'] %>% describe()# IFR/Fmt R2 w SEE

# Ramps IFR comparison plots
rampIBplot <- rampdf %>% ggplot(aes(x = KT, y = IBA)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 600)) +
  theme_bw()
rampDRplot <- rampdf %>% ggplot(aes(x = KT, y = DRA)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 350)) +
  theme_bw()
rampSRplot <- rampdf %>% ggplot(aes(x = KT, y = SRA)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 200)) +
  theme_bw()
rampDIplot <- rampdf %>% ggplot(aes(x = KT, y = DI)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 250)) +
  theme_bw()
ggarrange(rampIBplot, rampDRplot, rampSRplot, rampDIplot, nrow = 2,ncol = 2, legend = F)
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig3stats.eps', device = 'eps', plot = last_plot(), width = 4, height = 5, units = 'in')
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig3stats.jpg', device = 'jpg', plot = last_plot(), width = 4, height = 5, units = 'in')
```
# Triangles analysis
```{r}
# Triangles IFR comparisons
tridf %>% lmerTest::lmer(formula = triIB ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = trisc1 ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = trisc2 ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = trimifr1 ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = trimifr2 ~ KT + (1|unID)) %>% summary()

tridf %>% lmerTest::lmer(formula = scHD ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = mifrHD ~ KT + (1|unID)) %>% summary()

# regression R2
describe(tridf[c('rLmt', 'rLf', 'rFmt', 'rvmt', 'rvf')])
# regression slope comparisons
tridf %>% lmerTest::lmer(formula = mLf ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = mLmt ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = mvf ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = mvmt ~ KT + (1|unID)) %>% summary()
tridf %>% lmerTest::lmer(formula = mFmt ~ KT + (1|unID)) %>% summary()

# plotting
triIBplot <- tridf %>% ggplot(aes(x = KT, y = triIB)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 300)) +
  theme_bw()
trisc1plot <- tridf %>% ggplot(aes(x = KT, y = trisc1)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 150)) +
  theme_bw()
trisc2plot <- tridf %>% ggplot(aes(x = KT, y = trisc2)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 150)) +
  theme_bw()
trimifr1plot <- tridf %>% ggplot(aes(x = KT, y = trimifr1)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 200)) +
  theme_bw()
trimifr2plot <- tridf %>% ggplot(aes(x = KT, y = trimifr2)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 200)) +
  theme_bw()
triscHDplot <- tridf %>% ggplot(aes(x = KT, y = scHD)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 50)) +
  theme_bw()
trimifrHDplot <- tridf %>% ggplot(aes(x = KT, y = mifrHD)) +
  geom_violin() +
  geom_jitter(width = .1, height = 0) +
  geom_smooth(aes(group = unID), method = 'lm', se = F) +
  stat_summary(fun = mean, geom = 'crossbar') +
  ylim(c(0, 25)) +
  theme_bw()
ggarrange(trimifr1plot, trimifr2plot, triIBplot, trisc1plot, trisc2plot, {}, triscHDplot,  trimifrHDplot, nrow = 3, ncol = 3, legend = F)
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig4stats.eps', device = 'eps', plot = last_plot(),
       width = 5, height = 8, units = 'in')
ggsave('/Users/jacobstephens/Documents/Figures/Abbott_Stephens_manuscript/fig4stats.jpg', device = 'jpg', plot = last_plot())
```
